### ISSUE TITLE
nil should be ignored

### ISSUE THREAD

**Issue by concatime** [andrewchambers/janet-sh#11]
Hi,
is it possible to ignore `nil` values? Currently, it thows `error: unsupported argument nil`.
Thank you.

**Comment by andrewchambers** [comment]
It's not currently possible.

The current design is to help prevent accidents when you did not intend for a nil value to appear.

I tend to do something like:
```
(sh/$ echo ;(if foo [foo] []) )
```
instead.

**Comment by concatime** [comment]
Understandable. Yep, that’s what I was doing too.
