### ISSUE TITLE
Add support for piping long strings into command

### ISSUE THREAD

**Issue by autumnull** [andrewchambers/janet-sh#16]
One really good thing about this module is that it makes it easy to farm out already-implemented tasks to shell commands. There is an issue, though, which is that there is a limit on how long the argument list can be, so if you try to `echo` a long string to pipe it into another command, it throws an error: `spawn failed: "Argument list too long".`

I think it would be a great addition to the module to allow piping input into the shell command from a string within janet. Maybe the syntax could be something like this:
```janet
(def really-long-string "...")
(sh/$< [stdin really-long-string] | cat)
```

**Comment by andrewchambers** [comment]
iirc its already possible like:

(sh/$< cat < "hello")

**Comment by autumnull** [comment]
you're right that's my bad! that's really helpful, thank you :)
