### ISSUE TITLE
How to use shell variables?

### ISSUE THREAD

**Issue by MaxGyver83** [andrewchambers/janet-sh#22]
This doesn't work as expected (by me):

```
repl:8:> (sh/$ echo $PWD)
$PWD
```

It behaves like `echo '$PWD'`. How can I run an `echo "$PWD"`?

**Comment by ianthehenry** [comment]
janet-sh isn't trying to fully emulate a shell, so lots of shell features like `$variables`, `foo.{c,h}` expansion, subshells etc aren't implemented. If you want to read the value of an environment variable, you can use regular `(os/getenv "PWD")`, and pass that off to janet-sh:

```janet
(sh/$ echo ,(os/getenv "PWD"))
```

**Comment by MaxGyver83** [comment]
I see. Thank you for this clarification!
