### ISSUE TITLE
spawn failed: "No such file or directory"

### ISSUE THREAD

**Issue by kkharji** [andrewchambers/janet-sh#7]
Hey @andrewchambers, it would be nice if running something unidentified command will return stdout or stderr instead of erroring out. In my case I tried running a command line tool that wasn't installed, I'd like to have stderr with `command not found: ` rather that erroring out `No such file or directory`

Thanks

**Comment by andrewchambers** [comment]
Hmm, makes sense, this is consistent with what my shell does, though im not totally sure how to make it work given the way things are implemented.
